name: matchID
title: matchID project
email: martingross89@gmail.com
description: |
  Traitements d'identités
  <br/><br/>
  Entreprises, administrations, développeurs
  <br/>
  mettez en qualité et appariez vos bases de quelques milliers à cent millions d'identités
baseurl: ""
url: "https://matchid.io"
google_analytics: G-TEGXVTN15T

authors:
  - name: Fabien ANTOINE
    image: fabien.jpeg
    github: rhanka
    email: fabien.antoine@m4x.org
    desc: Fabien est ingénieur et travaille au sein de ministères régalien sur la data et l'IA.
          Concepteur de matchID et de deces.matchid.io, il développe toujours avec plaisir
          les algorithmes aussi bien que les UI, sur son temps libre.
    twitter: fabien_antoine
  - name: Cristian PEREZ BROKATE
    github: critianpb
    image: cristian.jpeg
    email: cristian.perez-brokate@interieur.gouv.fr
    twitter: cris_perez_b
    desc: Cristian est phD passionné de développement et technologie, expert en deeplearning. Il travaille
          aujourd'hui au ministère de l'Intérieur, où il a créé <a href="https://iaflash.fr">IA Flash</a>, et
          contribue activement à matchID avec la création de l'API décès.
  - name: Martin GROSS
    desc: Martin est ingénieur et cofondateur de <a href="https://commoprices.com">CommoPrices.com</a>, la plus grosse plateforme de prix de
          matières premières he world biggest portal of commodity prices.
          Il a développé l'interface de validation de matchID pendant son challenge EIG.
    github: tainmar
    image: martin.jpeg
    email: martingross89@gmail.com
    twitter: tainmar

project:
  general:
    name: matchID
    repo: matchID-project
  matchid_backend:
    name: automatisation des traitements
    repo: matchID-project/backend
    download: "https://github.com/matchID-project/backend/archive/master.zip"
  matchid_frontend:
    name: développement des traitements
    repo: matchID-project/frontend
    download: "https://github.com/matchID-project/frontend/archive/master.zip"
  examples:
    name: exemples de traitements
    repo: matchID-project/examples
    download: "https://github.com/matchID-project/examples/archive/master.zip"
  deces_backend:
    name: API décès
    repo: matchID-project/deces-backend
  deces_ui:
    name: moteur de recherche des décès
    repo: matchID-project/deces-ui
github_url: "https://github.com/"

# Build settings
github: [metadata]
theme: minima
markdown: kramdown

# sass:
#   style: compressed
#   sass_dir: _sass


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
